//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  blog: Blog;
  blogConnection: BlogConnection;
  page: Page;
  pageConnection: PageConnection;
  service: Service;
  serviceConnection: ServiceConnection;
  video: Video;
  videoConnection: VideoConnection;
  banner: Banner;
  bannerConnection: BannerConnection;
  feature: Feature;
  featureConnection: FeatureConnection;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QueryServiceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServiceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
};


export type QueryVideoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryVideoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<VideoFilter>;
};


export type QueryBannerArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBannerConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BannerFilter>;
};


export type QueryFeatureArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFeatureConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FeatureFilter>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};

export type DocumentFilter = {
  blog?: InputMaybe<BlogFilter>;
  page?: InputMaybe<PageFilter>;
  service?: InputMaybe<ServiceFilter>;
  video?: InputMaybe<VideoFilter>;
  banner?: InputMaybe<BannerFilter>;
  feature?: InputMaybe<FeatureFilter>;
  homepage?: InputMaybe<HomepageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Blog | Page | Service | Video | Banner | Feature | Homepage | Folder;

export type BlogSeo = {
  __typename?: 'BlogSeo';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type Blog = Node & Document & {
  __typename?: 'Blog';
  title: Scalars['String']['output'];
  excerpt: Scalars['String']['output'];
  featuredImage?: Maybe<Scalars['String']['output']>;
  publishDate: Scalars['String']['output'];
  publish?: Maybe<Scalars['Boolean']['output']>;
  categories?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  seo?: Maybe<BlogSeo>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BlogSeoFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<StringFilter>;
};

export type BlogFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  featuredImage?: InputMaybe<ImageFilter>;
  publishDate?: InputMaybe<DatetimeFilter>;
  publish?: InputMaybe<BooleanFilter>;
  categories?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  seo?: InputMaybe<BlogSeoFilter>;
};

export type BlogConnectionEdges = {
  __typename?: 'BlogConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blog>;
};

export type BlogConnection = Connection & {
  __typename?: 'BlogConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogConnectionEdges>>>;
};

export type PageSeo = {
  __typename?: 'PageSeo';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type Page = Node & Document & {
  __typename?: 'Page';
  title: Scalars['String']['output'];
  excerpt?: Maybe<Scalars['String']['output']>;
  publish?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  seo?: Maybe<PageSeo>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageSeoFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type PageFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  publish?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
  seo?: InputMaybe<PageSeoFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type Service = Node & Document & {
  __typename?: 'Service';
  title: Scalars['String']['output'];
  excerpt?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ServiceFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  icon?: InputMaybe<ImageFilter>;
  link?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ServiceConnectionEdges = {
  __typename?: 'ServiceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Service>;
};

export type ServiceConnection = Connection & {
  __typename?: 'ServiceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServiceConnectionEdges>>>;
};

export type Video = Node & Document & {
  __typename?: 'Video';
  title: Scalars['String']['output'];
  videoUrl: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  thumbnail?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type VideoFilter = {
  title?: InputMaybe<StringFilter>;
  videoUrl?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type VideoConnectionEdges = {
  __typename?: 'VideoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Video>;
};

export type VideoConnection = Connection & {
  __typename?: 'VideoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<VideoConnectionEdges>>>;
};

export type Banner = Node & Document & {
  __typename?: 'Banner';
  title: Scalars['String']['output'];
  image: Scalars['String']['output'];
  link?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  active?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BannerFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  link?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  active?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BannerConnectionEdges = {
  __typename?: 'BannerConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Banner>;
};

export type BannerConnection = Connection & {
  __typename?: 'BannerConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BannerConnectionEdges>>>;
};

export type Feature = Node & Document & {
  __typename?: 'Feature';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  icon: Scalars['String']['output'];
  order: Scalars['Float']['output'];
  active?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FeatureFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  active?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type FeatureConnectionEdges = {
  __typename?: 'FeatureConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Feature>;
};

export type FeatureConnection = Connection & {
  __typename?: 'FeatureConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FeatureConnectionEdges>>>;
};

export type HomepageHero = {
  __typename?: 'HomepageHero';
  heroTitle: Scalars['String']['output'];
  heroDescription: Scalars['String']['output'];
  heroImage?: Maybe<Scalars['String']['output']>;
  heroOverlayOpacity?: Maybe<Scalars['Float']['output']>;
  heroButton1Text: Scalars['String']['output'];
  heroButton1Link: Scalars['String']['output'];
  heroButton2Text: Scalars['String']['output'];
  heroButton2Link: Scalars['String']['output'];
};

export type HomepageFeatures = {
  __typename?: 'HomepageFeatures';
  featuresEyebrow: Scalars['String']['output'];
  featuresTitle: Scalars['String']['output'];
  featuresDescription: Scalars['String']['output'];
  featuresButtonText: Scalars['String']['output'];
  featuresButtonLink: Scalars['String']['output'];
};

export type HomepageMainCta = {
  __typename?: 'HomepageMainCta';
  mainCtaEyebrow: Scalars['String']['output'];
  mainCtaTitle: Scalars['String']['output'];
  mainCtaDescription: Scalars['String']['output'];
  mainCtaButtonText: Scalars['String']['output'];
  mainCtaButtonLink: Scalars['String']['output'];
};

export type HomepageFooterCta = {
  __typename?: 'HomepageFooterCta';
  footerCtaEyebrow: Scalars['String']['output'];
  footerCtaTitle: Scalars['String']['output'];
  footerCtaDescription: Scalars['String']['output'];
  footerCtaButtonText: Scalars['String']['output'];
  footerCtaButtonLink: Scalars['String']['output'];
};

export type HomepageRecentPosts = {
  __typename?: 'HomepageRecentPosts';
  recentPostsEyebrow: Scalars['String']['output'];
  recentPostsTitle: Scalars['String']['output'];
  recentPostsDescription: Scalars['String']['output'];
  recentPostsButtonText: Scalars['String']['output'];
  recentPostsButtonLink: Scalars['String']['output'];
  recentPostsCount?: Maybe<Scalars['Float']['output']>;
};

export type HomepageSeo = {
  __typename?: 'HomepageSeo';
  seoTitle: Scalars['String']['output'];
  seoDescription: Scalars['String']['output'];
};

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  title: Scalars['String']['output'];
  hero?: Maybe<HomepageHero>;
  features?: Maybe<HomepageFeatures>;
  mainCta?: Maybe<HomepageMainCta>;
  footerCta?: Maybe<HomepageFooterCta>;
  recentPosts?: Maybe<HomepageRecentPosts>;
  seo?: Maybe<HomepageSeo>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomepageHeroFilter = {
  heroTitle?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  heroOverlayOpacity?: InputMaybe<NumberFilter>;
  heroButton1Text?: InputMaybe<StringFilter>;
  heroButton1Link?: InputMaybe<StringFilter>;
  heroButton2Text?: InputMaybe<StringFilter>;
  heroButton2Link?: InputMaybe<StringFilter>;
};

export type HomepageFeaturesFilter = {
  featuresEyebrow?: InputMaybe<StringFilter>;
  featuresTitle?: InputMaybe<StringFilter>;
  featuresDescription?: InputMaybe<StringFilter>;
  featuresButtonText?: InputMaybe<StringFilter>;
  featuresButtonLink?: InputMaybe<StringFilter>;
};

export type HomepageMainCtaFilter = {
  mainCtaEyebrow?: InputMaybe<StringFilter>;
  mainCtaTitle?: InputMaybe<StringFilter>;
  mainCtaDescription?: InputMaybe<StringFilter>;
  mainCtaButtonText?: InputMaybe<StringFilter>;
  mainCtaButtonLink?: InputMaybe<StringFilter>;
};

export type HomepageFooterCtaFilter = {
  footerCtaEyebrow?: InputMaybe<StringFilter>;
  footerCtaTitle?: InputMaybe<StringFilter>;
  footerCtaDescription?: InputMaybe<StringFilter>;
  footerCtaButtonText?: InputMaybe<StringFilter>;
  footerCtaButtonLink?: InputMaybe<StringFilter>;
};

export type HomepageRecentPostsFilter = {
  recentPostsEyebrow?: InputMaybe<StringFilter>;
  recentPostsTitle?: InputMaybe<StringFilter>;
  recentPostsDescription?: InputMaybe<StringFilter>;
  recentPostsButtonText?: InputMaybe<StringFilter>;
  recentPostsButtonLink?: InputMaybe<StringFilter>;
  recentPostsCount?: InputMaybe<NumberFilter>;
};

export type HomepageSeoFilter = {
  seoTitle?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
};

export type HomepageFilter = {
  title?: InputMaybe<StringFilter>;
  hero?: InputMaybe<HomepageHeroFilter>;
  features?: InputMaybe<HomepageFeaturesFilter>;
  mainCta?: InputMaybe<HomepageMainCtaFilter>;
  footerCta?: InputMaybe<HomepageFooterCtaFilter>;
  recentPosts?: InputMaybe<HomepageRecentPostsFilter>;
  seo?: InputMaybe<HomepageSeoFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateBlog: Blog;
  createBlog: Blog;
  updatePage: Page;
  createPage: Page;
  updateService: Service;
  createService: Service;
  updateVideo: Video;
  createVideo: Video;
  updateBanner: Banner;
  createBanner: Banner;
  updateFeature: Feature;
  createFeature: Feature;
  updateHomepage: Homepage;
  createHomepage: Homepage;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationCreateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationCreateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationUpdateVideoArgs = {
  relativePath: Scalars['String']['input'];
  params: VideoMutation;
};


export type MutationCreateVideoArgs = {
  relativePath: Scalars['String']['input'];
  params: VideoMutation;
};


export type MutationUpdateBannerArgs = {
  relativePath: Scalars['String']['input'];
  params: BannerMutation;
};


export type MutationCreateBannerArgs = {
  relativePath: Scalars['String']['input'];
  params: BannerMutation;
};


export type MutationUpdateFeatureArgs = {
  relativePath: Scalars['String']['input'];
  params: FeatureMutation;
};


export type MutationCreateFeatureArgs = {
  relativePath: Scalars['String']['input'];
  params: FeatureMutation;
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};

export type DocumentUpdateMutation = {
  blog?: InputMaybe<BlogMutation>;
  page?: InputMaybe<PageMutation>;
  service?: InputMaybe<ServiceMutation>;
  video?: InputMaybe<VideoMutation>;
  banner?: InputMaybe<BannerMutation>;
  feature?: InputMaybe<FeatureMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  blog?: InputMaybe<BlogMutation>;
  page?: InputMaybe<PageMutation>;
  service?: InputMaybe<ServiceMutation>;
  video?: InputMaybe<VideoMutation>;
  banner?: InputMaybe<BannerMutation>;
  feature?: InputMaybe<FeatureMutation>;
  homepage?: InputMaybe<HomepageMutation>;
};

export type BlogSeoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type BlogMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  featuredImage?: InputMaybe<Scalars['String']['input']>;
  publishDate?: InputMaybe<Scalars['String']['input']>;
  publish?: InputMaybe<Scalars['Boolean']['input']>;
  categories?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  seo?: InputMaybe<BlogSeoMutation>;
};

export type PageSeoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type PageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  publish?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  seo?: InputMaybe<PageSeoMutation>;
};

export type ServiceMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type VideoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  videoUrl?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  thumbnail?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type BannerMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  active?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type FeatureMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  active?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type HomepageHeroMutation = {
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  heroOverlayOpacity?: InputMaybe<Scalars['Float']['input']>;
  heroButton1Text?: InputMaybe<Scalars['String']['input']>;
  heroButton1Link?: InputMaybe<Scalars['String']['input']>;
  heroButton2Text?: InputMaybe<Scalars['String']['input']>;
  heroButton2Link?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageFeaturesMutation = {
  featuresEyebrow?: InputMaybe<Scalars['String']['input']>;
  featuresTitle?: InputMaybe<Scalars['String']['input']>;
  featuresDescription?: InputMaybe<Scalars['String']['input']>;
  featuresButtonText?: InputMaybe<Scalars['String']['input']>;
  featuresButtonLink?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageMainCtaMutation = {
  mainCtaEyebrow?: InputMaybe<Scalars['String']['input']>;
  mainCtaTitle?: InputMaybe<Scalars['String']['input']>;
  mainCtaDescription?: InputMaybe<Scalars['String']['input']>;
  mainCtaButtonText?: InputMaybe<Scalars['String']['input']>;
  mainCtaButtonLink?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageFooterCtaMutation = {
  footerCtaEyebrow?: InputMaybe<Scalars['String']['input']>;
  footerCtaTitle?: InputMaybe<Scalars['String']['input']>;
  footerCtaDescription?: InputMaybe<Scalars['String']['input']>;
  footerCtaButtonText?: InputMaybe<Scalars['String']['input']>;
  footerCtaButtonLink?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageRecentPostsMutation = {
  recentPostsEyebrow?: InputMaybe<Scalars['String']['input']>;
  recentPostsTitle?: InputMaybe<Scalars['String']['input']>;
  recentPostsDescription?: InputMaybe<Scalars['String']['input']>;
  recentPostsButtonText?: InputMaybe<Scalars['String']['input']>;
  recentPostsButtonLink?: InputMaybe<Scalars['String']['input']>;
  recentPostsCount?: InputMaybe<Scalars['Float']['input']>;
};

export type HomepageSeoMutation = {
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  hero?: InputMaybe<HomepageHeroMutation>;
  features?: InputMaybe<HomepageFeaturesMutation>;
  mainCta?: InputMaybe<HomepageMainCtaMutation>;
  footerCta?: InputMaybe<HomepageFooterCtaMutation>;
  recentPosts?: InputMaybe<HomepageRecentPostsMutation>;
  seo?: InputMaybe<HomepageSeoMutation>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type BlogPartsFragment = { __typename: 'Blog', title: string, excerpt: string, featuredImage?: string | null, publishDate: string, publish?: boolean | null, categories?: Array<string | null> | null, tags?: Array<string | null> | null, body?: any | null, seo?: { __typename: 'BlogSeo', title?: string | null, description?: string | null, image?: string | null } | null };

export type PagePartsFragment = { __typename: 'Page', title: string, excerpt?: string | null, publish?: boolean | null, body?: any | null, seo?: { __typename: 'PageSeo', title?: string | null, description?: string | null } | null };

export type ServicePartsFragment = { __typename: 'Service', title: string, excerpt?: string | null, icon?: string | null, link?: string | null, order?: number | null, body?: any | null };

export type VideoPartsFragment = { __typename: 'Video', title: string, videoUrl: string, category?: string | null, thumbnail?: string | null, body?: any | null };

export type BannerPartsFragment = { __typename: 'Banner', title: string, image: string, link?: string | null, order?: number | null, active?: boolean | null, body?: any | null };

export type FeaturePartsFragment = { __typename: 'Feature', title: string, description: string, icon: string, order: number, active?: boolean | null, body?: any | null };

export type HomepagePartsFragment = { __typename: 'Homepage', title: string, body?: any | null, hero?: { __typename: 'HomepageHero', heroTitle: string, heroDescription: string, heroImage?: string | null, heroOverlayOpacity?: number | null, heroButton1Text: string, heroButton1Link: string, heroButton2Text: string, heroButton2Link: string } | null, features?: { __typename: 'HomepageFeatures', featuresEyebrow: string, featuresTitle: string, featuresDescription: string, featuresButtonText: string, featuresButtonLink: string } | null, mainCta?: { __typename: 'HomepageMainCta', mainCtaEyebrow: string, mainCtaTitle: string, mainCtaDescription: string, mainCtaButtonText: string, mainCtaButtonLink: string } | null, footerCta?: { __typename: 'HomepageFooterCta', footerCtaEyebrow: string, footerCtaTitle: string, footerCtaDescription: string, footerCtaButtonText: string, footerCtaButtonLink: string } | null, recentPosts?: { __typename: 'HomepageRecentPosts', recentPostsEyebrow: string, recentPostsTitle: string, recentPostsDescription: string, recentPostsButtonText: string, recentPostsButtonLink: string, recentPostsCount?: number | null } | null, seo?: { __typename: 'HomepageSeo', seoTitle: string, seoDescription: string } | null };

export type BlogQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogQuery = { __typename?: 'Query', blog: { __typename: 'Blog', id: string, title: string, excerpt: string, featuredImage?: string | null, publishDate: string, publish?: boolean | null, categories?: Array<string | null> | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'BlogSeo', title?: string | null, description?: string | null, image?: string | null } | null } };

export type BlogConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
}>;


export type BlogConnectionQuery = { __typename?: 'Query', blogConnection: { __typename?: 'BlogConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogConnectionEdges', cursor: string, node?: { __typename: 'Blog', id: string, title: string, excerpt: string, featuredImage?: string | null, publishDate: string, publish?: boolean | null, categories?: Array<string | null> | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'BlogSeo', title?: string | null, description?: string | null, image?: string | null } | null } | null } | null> | null } };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, title: string, excerpt?: string | null, publish?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'PageSeo', title?: string | null, description?: string | null } | null } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, title: string, excerpt?: string | null, publish?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'PageSeo', title?: string | null, description?: string | null } | null } | null } | null> | null } };

export type ServiceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServiceQuery = { __typename?: 'Query', service: { __typename: 'Service', id: string, title: string, excerpt?: string | null, icon?: string | null, link?: string | null, order?: number | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ServiceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
}>;


export type ServiceConnectionQuery = { __typename?: 'Query', serviceConnection: { __typename?: 'ServiceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServiceConnectionEdges', cursor: string, node?: { __typename: 'Service', id: string, title: string, excerpt?: string | null, icon?: string | null, link?: string | null, order?: number | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type VideoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type VideoQuery = { __typename?: 'Query', video: { __typename: 'Video', id: string, title: string, videoUrl: string, category?: string | null, thumbnail?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type VideoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<VideoFilter>;
}>;


export type VideoConnectionQuery = { __typename?: 'Query', videoConnection: { __typename?: 'VideoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'VideoConnectionEdges', cursor: string, node?: { __typename: 'Video', id: string, title: string, videoUrl: string, category?: string | null, thumbnail?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type BannerQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BannerQuery = { __typename?: 'Query', banner: { __typename: 'Banner', id: string, title: string, image: string, link?: string | null, order?: number | null, active?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BannerConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BannerFilter>;
}>;


export type BannerConnectionQuery = { __typename?: 'Query', bannerConnection: { __typename?: 'BannerConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BannerConnectionEdges', cursor: string, node?: { __typename: 'Banner', id: string, title: string, image: string, link?: string | null, order?: number | null, active?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type FeatureQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FeatureQuery = { __typename?: 'Query', feature: { __typename: 'Feature', id: string, title: string, description: string, icon: string, order: number, active?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type FeatureConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FeatureFilter>;
}>;


export type FeatureConnectionQuery = { __typename?: 'Query', featureConnection: { __typename?: 'FeatureConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FeatureConnectionEdges', cursor: string, node?: { __typename: 'Feature', id: string, title: string, description: string, icon: string, order: number, active?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomepageHero', heroTitle: string, heroDescription: string, heroImage?: string | null, heroOverlayOpacity?: number | null, heroButton1Text: string, heroButton1Link: string, heroButton2Text: string, heroButton2Link: string } | null, features?: { __typename: 'HomepageFeatures', featuresEyebrow: string, featuresTitle: string, featuresDescription: string, featuresButtonText: string, featuresButtonLink: string } | null, mainCta?: { __typename: 'HomepageMainCta', mainCtaEyebrow: string, mainCtaTitle: string, mainCtaDescription: string, mainCtaButtonText: string, mainCtaButtonLink: string } | null, footerCta?: { __typename: 'HomepageFooterCta', footerCtaEyebrow: string, footerCtaTitle: string, footerCtaDescription: string, footerCtaButtonText: string, footerCtaButtonLink: string } | null, recentPosts?: { __typename: 'HomepageRecentPosts', recentPostsEyebrow: string, recentPostsTitle: string, recentPostsDescription: string, recentPostsButtonText: string, recentPostsButtonLink: string, recentPostsCount?: number | null } | null, seo?: { __typename: 'HomepageSeo', seoTitle: string, seoDescription: string } | null } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomepageHero', heroTitle: string, heroDescription: string, heroImage?: string | null, heroOverlayOpacity?: number | null, heroButton1Text: string, heroButton1Link: string, heroButton2Text: string, heroButton2Link: string } | null, features?: { __typename: 'HomepageFeatures', featuresEyebrow: string, featuresTitle: string, featuresDescription: string, featuresButtonText: string, featuresButtonLink: string } | null, mainCta?: { __typename: 'HomepageMainCta', mainCtaEyebrow: string, mainCtaTitle: string, mainCtaDescription: string, mainCtaButtonText: string, mainCtaButtonLink: string } | null, footerCta?: { __typename: 'HomepageFooterCta', footerCtaEyebrow: string, footerCtaTitle: string, footerCtaDescription: string, footerCtaButtonText: string, footerCtaButtonLink: string } | null, recentPosts?: { __typename: 'HomepageRecentPosts', recentPostsEyebrow: string, recentPostsTitle: string, recentPostsDescription: string, recentPostsButtonText: string, recentPostsButtonLink: string, recentPostsCount?: number | null } | null, seo?: { __typename: 'HomepageSeo', seoTitle: string, seoDescription: string } | null } | null } | null> | null } };

export const BlogPartsFragmentDoc = gql`
    fragment BlogParts on Blog {
  __typename
  title
  excerpt
  featuredImage
  publishDate
  publish
  categories
  tags
  body
  seo {
    __typename
    title
    description
    image
  }
}
    `;
export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  title
  excerpt
  publish
  body
  seo {
    __typename
    title
    description
  }
}
    `;
export const ServicePartsFragmentDoc = gql`
    fragment ServiceParts on Service {
  __typename
  title
  excerpt
  icon
  link
  order
  body
}
    `;
export const VideoPartsFragmentDoc = gql`
    fragment VideoParts on Video {
  __typename
  title
  videoUrl
  category
  thumbnail
  body
}
    `;
export const BannerPartsFragmentDoc = gql`
    fragment BannerParts on Banner {
  __typename
  title
  image
  link
  order
  active
  body
}
    `;
export const FeaturePartsFragmentDoc = gql`
    fragment FeatureParts on Feature {
  __typename
  title
  description
  icon
  order
  active
  body
}
    `;
export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  title
  hero {
    __typename
    heroTitle
    heroDescription
    heroImage
    heroOverlayOpacity
    heroButton1Text
    heroButton1Link
    heroButton2Text
    heroButton2Link
  }
  features {
    __typename
    featuresEyebrow
    featuresTitle
    featuresDescription
    featuresButtonText
    featuresButtonLink
  }
  mainCta {
    __typename
    mainCtaEyebrow
    mainCtaTitle
    mainCtaDescription
    mainCtaButtonText
    mainCtaButtonLink
  }
  footerCta {
    __typename
    footerCtaEyebrow
    footerCtaTitle
    footerCtaDescription
    footerCtaButtonText
    footerCtaButtonLink
  }
  recentPosts {
    __typename
    recentPostsEyebrow
    recentPostsTitle
    recentPostsDescription
    recentPostsButtonText
    recentPostsButtonLink
    recentPostsCount
  }
  seo {
    __typename
    seoTitle
    seoDescription
  }
  body
}
    `;
export const BlogDocument = gql`
    query blog($relativePath: String!) {
  blog(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogParts
  }
}
    ${BlogPartsFragmentDoc}`;
export const BlogConnectionDocument = gql`
    query blogConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogFilter) {
  blogConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogParts
      }
    }
  }
}
    ${BlogPartsFragmentDoc}`;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const ServiceDocument = gql`
    query service($relativePath: String!) {
  service(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServiceParts
  }
}
    ${ServicePartsFragmentDoc}`;
export const ServiceConnectionDocument = gql`
    query serviceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServiceFilter) {
  serviceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServiceParts
      }
    }
  }
}
    ${ServicePartsFragmentDoc}`;
export const VideoDocument = gql`
    query video($relativePath: String!) {
  video(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...VideoParts
  }
}
    ${VideoPartsFragmentDoc}`;
export const VideoConnectionDocument = gql`
    query videoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: VideoFilter) {
  videoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...VideoParts
      }
    }
  }
}
    ${VideoPartsFragmentDoc}`;
export const BannerDocument = gql`
    query banner($relativePath: String!) {
  banner(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BannerParts
  }
}
    ${BannerPartsFragmentDoc}`;
export const BannerConnectionDocument = gql`
    query bannerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BannerFilter) {
  bannerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BannerParts
      }
    }
  }
}
    ${BannerPartsFragmentDoc}`;
export const FeatureDocument = gql`
    query feature($relativePath: String!) {
  feature(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FeatureParts
  }
}
    ${FeaturePartsFragmentDoc}`;
export const FeatureConnectionDocument = gql`
    query featureConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FeatureFilter) {
  featureConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FeatureParts
      }
    }
  }
}
    ${FeaturePartsFragmentDoc}`;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      blog(variables: BlogQueryVariables, options?: C): Promise<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}> {
        return requester<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}, BlogQueryVariables>(BlogDocument, variables, options);
      },
    blogConnection(variables?: BlogConnectionQueryVariables, options?: C): Promise<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}> {
        return requester<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}, BlogConnectionQueryVariables>(BlogConnectionDocument, variables, options);
      },
    page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    service(variables: ServiceQueryVariables, options?: C): Promise<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}> {
        return requester<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}, ServiceQueryVariables>(ServiceDocument, variables, options);
      },
    serviceConnection(variables?: ServiceConnectionQueryVariables, options?: C): Promise<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}> {
        return requester<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}, ServiceConnectionQueryVariables>(ServiceConnectionDocument, variables, options);
      },
    video(variables: VideoQueryVariables, options?: C): Promise<{data: VideoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideoQueryVariables, query: string}> {
        return requester<{data: VideoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideoQueryVariables, query: string}, VideoQueryVariables>(VideoDocument, variables, options);
      },
    videoConnection(variables?: VideoConnectionQueryVariables, options?: C): Promise<{data: VideoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideoConnectionQueryVariables, query: string}> {
        return requester<{data: VideoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VideoConnectionQueryVariables, query: string}, VideoConnectionQueryVariables>(VideoConnectionDocument, variables, options);
      },
    banner(variables: BannerQueryVariables, options?: C): Promise<{data: BannerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BannerQueryVariables, query: string}> {
        return requester<{data: BannerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BannerQueryVariables, query: string}, BannerQueryVariables>(BannerDocument, variables, options);
      },
    bannerConnection(variables?: BannerConnectionQueryVariables, options?: C): Promise<{data: BannerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BannerConnectionQueryVariables, query: string}> {
        return requester<{data: BannerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BannerConnectionQueryVariables, query: string}, BannerConnectionQueryVariables>(BannerConnectionDocument, variables, options);
      },
    feature(variables: FeatureQueryVariables, options?: C): Promise<{data: FeatureQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeatureQueryVariables, query: string}> {
        return requester<{data: FeatureQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeatureQueryVariables, query: string}, FeatureQueryVariables>(FeatureDocument, variables, options);
      },
    featureConnection(variables?: FeatureConnectionQueryVariables, options?: C): Promise<{data: FeatureConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeatureConnectionQueryVariables, query: string}> {
        return requester<{data: FeatureConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeatureConnectionQueryVariables, query: string}, FeatureConnectionQueryVariables>(FeatureConnectionDocument, variables, options);
      },
    homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  